[image]
art = "samples/getting-started/img.jpg"
bg_color = "#54130C"

[text]
text = "samples/getting-started/text.txt"
text_box_pos = "split"

# https://unsplash.com/photos/a-person-in-a-garment-EpTIAbTlrg0
credits = [
	"Photo: Ryan Yao on Unsplash"
]

[output]
base_filename = "test"
output_directory = "samples/getting-started"

[[characters]]
name = "serif"
color = "#F0C7C2"
font = "fonts/Noto_Serif/NotoSerif-Regular.ttf"
font_bold = "fonts/Noto_Serif/NotoSerif-Bold.ttf"
font_italic = "fonts/Noto_Serif/NotoSerif-Italic.ttf"
font_bolditalic = "fonts/Noto_Serif/NotoSerif-BoldItalic.ttf"

[[characters]]
name = "sans"
color = "#C2EFF0"
relative_height = 0.7
font = "fonts/Noto_Sans/NotoSans-Regular.ttf"

[[characters]]
name = "em"
color = "#FFFFFF"
font = "fonts/Noto_Emoji/NotoEmoji-Regular.ttf"
